---
# Clean
- hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ rg_name }}"
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        force_delete_nonempty: yes
        state: absent
      register: rg
    - debug:
        var: rg
...
